# frozen_string_literal: true

# logo map 50x50
# dest

module Engine
  module Game
    module G18Turkey
      module Corporations
        CORPORATIONS = [
          {
            float_percent: 60,
            sym: 'OE',
            name: 'Orient-Expressen',
            logo: '18_turkey/OE',
            simple_logo: '18_turkey/OE.alt',
            color: '#669d49',
            reservation_color: '#669d49',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'C5',
            city: 0,
          },
          {
            float_percent: 60,
            sym: 'BB',
            name: 'Bagdadbahn',
            logo: '18_turkey/BB',
            simple_logo: '18_turkey/BB.alt',
            color: '#97679c',
            reservation_color: '#97679c',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'F12',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'AE',
            name: 'Anatolische Eisenbahn',
            logo: '18_turkey/AE',
            simple_logo: '18_turkey/AE.alt',
            color: '#73a9bd',
            reservation_color: '#73a9bd',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'E7',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'TR',
            name: 'Transcaucasus',
            logo: '18_turkey/TR',
            simple_logo: '18_turkey/TR.alt',
            color: '#e6924e',
            reservation_color: '#e6924e',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'K5',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'MTA',
            name: 'Mersin-Tarsus-Adana',
            logo: '18_turkey/MTA',
            simple_logo: '18_turkey/MTA.alt',
            color: '#a2c26a',
            reservation_color: '#a2c26a',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'E13',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'DHE',
            name: 'Damas-Hamah & Extensions',
            logo: '18_turkey/DHE',
            simple_logo: '18_turkey/DHE.alt',
            color: '#43c6db',
            reservation_color: '#43c6db',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'H14',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'ORC',
            name: 'Ottoman Railway Company',
            logo: '18_turkey/ORC',
            simple_logo: '18_turkey/ORC.alt',
            color: '#fff104',
            reservation_color: '#fff104',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'B10',
          },
          {
            float_percent: 60,
            sym: 'SCR',
            name: 'Smyrna Cassaba Railway',
            logo: '18_turkey/SCR',
            simple_logo: '18_turkey/SCR.alt',
            color: '#fad5e4',
            reservation_color: '#fad5e4',
            tokens: [0, 40, 60],
            shares: [40, 20, 20, 20],
            text_color: 'black',
            coordinates: 'B12',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'CNR',
            name: 'Citicia & North Syria Railways',
            logo: '18_turkey/CNR',
            simple_logo: '18_turkey/CNR.alt',
            color: '#9b7546',
            reservation_color: '#9b7546',
            tokens: [0, 40, 60],
            text_color: 'black',
            coordinates: 'I11',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'SCRX',
            name: 'Samsun Coastal Railways',
            logo: '18_turkey/SCRX',
            simple_logo: '18_turkey/SCRX.alt',
            color: '#ddd3c4',
            reservation_color: '#ddd3c4',
            tokens: [0, 40, 60],
            text_color: 'black',
            coordinates: 'G5',
            abilities: [],
          },
          {
            float_percent: 60,
            sym: 'TCDD',
            name: 'Türkiye Cumhuriyeti Devlet Demiryollari',
            logo: '18_turkey/TCDD',
            simple_logo: '18_turkey/TCDD.alt',
            color: '#6d76aa',
            reservation_color: '#6d76aa',
            tokens: [0, 40, 60],
            text_color: 'black',
            coordinates: 'G5',
            abilities: [],
          },
          ].freeze
      end
    end
  end
end
